version: '2'

services:

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_NODE=false
                - INSTALL_DRUSH=false
                - INSTALL_AEROSPIKE_EXTENSION=true
                - COMPOSER_GLOBAL_INSTALL=false
                - INSTALL_WORKSPACE_SSH=false
                - PUID=1000
                - PGID=1000
                - NODE_VERSION=stable
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:${EXTERNAL_IP}"
        ports:
           - "2022:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_AEROSPIKE_EXTENSION=true
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:${EXTERNAL_IP}"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ../../log/nginx:/var/log/nginx
        ports:
            - "2080:80"
            - "2043:443"
        links:
            - php-fpm

### MariaDB Container #######################################

    mariadb:
        build: ./mariadb
        volumes_from:
            - volumes_data
        #ports:
        #    - "1106:3306"
        environment:
            MYSQL_DATABASE: cert
            MYSQL_USER: cert
            MYSQL_PASSWORD: Xx56#L02a1
            MYSQL_ROOT_PASSWORD: Xx56#L02a1

### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - volumes_data
        #ports:
        #    - "1179:6379"

### phpMyAdmin Container ##################################

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: th_deploy
            MYSQL_PASSWORD: Xx56#L02a1
            MYSQL_ROOT_PASSWORD: Xx56#L02a1
        volumes_from:
            - volumes_data
        ports:
            - "2081:80"
        links:
            - "mariadb:db"

### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../../web:/var/www/laravel
            - ../../config:/var/www/config
            - ../../log/www:/var/www/log

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ../../data/mysql:/var/lib/mysql
            - ../../data/redis:/data
            - ../../data/sessions:/sessions

### Add more Containers below ###############################
